homepage:
  path: /
  controller: App\Controller\DefaultController::indexAction

login:
  path: /login
  controller: App\Controller\SecurityController::loginAction

login_check:
  path: /login_check

logout:
  path: /logout

task_list_admin:
  path: /admin/tasks
  controller: App\Controller\TaskController::listAdminNotDone

task_list_admin_done:
  path: /admin/tasks/done
  controller: App\Controller\TaskController::listAdminIsDone

task_list:
  path: /tasks
  controller: App\Controller\TaskController::listAction

task_list_done:
  path: /tasks/done
  controller: App\Controller\TaskController::listIsDoneAction

task_create:
  path: /tasks/create
  controller: App\Controller\TaskController::createAction

task_edit:
  path: /tasks/edit/{id}
  controller: App\Controller\TaskController::editAction

task_toggle:
  path: /tasks/toggle/{id}
  controller: App\Controller\TaskController::toggleTaskAction

task_delete:
  path: /tasks/delete/{id}
  controller: App\Controller\TaskController::deleteTaskAction

user_list:
  path: /users
  controller: App\Controller\UserController::listAction

user_create:
  path: /users/create
  controller: App\Controller\UserController::createAction

user_edit:
  path: /users/edit/{id}
  controller: App\Controller\UserController::editAction

user_delete:
  path: /users/delete/{id}
  controller: App\Controller\UserController::deleteAction


#index:
#    path: /
#    controller: App\Controller\DefaultController::index
